import * as THREE from 'three';
import { MarchingCubes } from 'three/addons/objects/MarchingCubes.js';

// Giant lava lamp. The wax inside is an isosurface generated by a small
// MarchingCubes grid each frame from N moving metaballs — when two
// blobs drift close their fields merge into a single morphing shape;
// when they drift apart they pinch off into separate blobs. That's the
// defining visual of a real lava lamp and a plain sphere-blob can't
// reproduce it.
//
// Physics is biased UPWARD: at neutral temperature blobs still rise
// slowly. Cooling at the top is gradual; heating at the bottom is fast.
// Net effect: blobs spend most of their time rising, occasionally one
// reaches the top, cools, and slowly drifts back down — what real lava
// lamps actually do.
export class LavaLamp extends THREE.Group {
  constructor({
    height = 7.5,
    vesselRadius = 0.55,
    blobCount = 6,
    bulbColor = 0xffa860,
    bulbIntensity = 9.0,
    waxColor = 0xff4828,
    waxEmissive = 0xff3818,
  } = {}) {
    super();

    this.vesselHeight = height;
    this.vesselRadius = vesselRadius;

    const metalMat = new THREE.MeshPhysicalMaterial({
      color: 0x1a1a1e, roughness: 0.35, metalness: 0.88,
      clearcoat: 0.5, clearcoatRoughness: 0.18,
    });

    // ---- Base ----
    const baseHeight = 0.7;
    const base = new THREE.Mesh(
      new THREE.CylinderGeometry(vesselRadius * 1.35, vesselRadius * 1.5, baseHeight, 28),
      metalMat,
    );
    base.position.y = baseHeight / 2;
    base.castShadow = true;
    base.receiveShadow = true;
    this.add(base);

    // ---- Glass vessel ----
    // Alpha-transparent rather than refractive. With 4 lamps each
    // contributing a transmissive shell, the backdrop pass cost added
    // up to noticeable frame-rate hit on MED/HIGH quality. Plain alpha
    // composites through nested transparent layers for free and
    // doesn't trigger the second scene render.
    // (The arch glass columns still use full transmission — only one
    // pair of them, refraction look intact there.)
    const glass = new THREE.Mesh(
      new THREE.CylinderGeometry(vesselRadius, vesselRadius, height, 64, 1, true),
      new THREE.MeshPhysicalMaterial({
        color: 0xfff5e8,
        roughness: 0.06,
        metalness: 0.0,
        transparent: true,
        opacity: 0.28,
        side: THREE.DoubleSide,
        clearcoat: 0.85,
        clearcoatRoughness: 0.06,
        depthWrite: false,
      }),
    );
    glass.position.y = baseHeight + height / 2;
    this.add(glass);
    this.vesselBottomY = baseHeight;
    this.vesselTopY = baseHeight + height;

    // ---- Neck + cap ----
    const neckHeight = 0.25;
    const neck = new THREE.Mesh(
      new THREE.CylinderGeometry(vesselRadius * 0.55, vesselRadius * 1.05, neckHeight, 24),
      metalMat,
    );
    neck.position.y = baseHeight + height + neckHeight / 2;
    this.add(neck);
    const cap = new THREE.Mesh(
      new THREE.ConeGeometry(vesselRadius * 0.55, 0.5, 24),
      metalMat,
    );
    cap.position.y = baseHeight + height + neckHeight + 0.25;
    this.add(cap);

    // ---- Marching-cubes wax ----
    // Resolution 20³ = 8000 cells. Each frame we reset, place metaballs,
    // and trigger the surface generation. The MC object's local volume
    // is normalised to [0,1]³; we scale it into the vessel's interior
    // (~85% of the vessel radius so the wax never visibly clips the
    // glass wall).
    const resolution = 22;
    const waxMat = new THREE.MeshPhysicalMaterial({
      // Opaque wax. Real lava lamp wax doesn't transmit light — it just
      // glows brightly via emissive lit from below by the bulb. Skipping
      // transmission here also avoids further nesting in the
      // transmission buffer (the column / brick / glass layers already
      // saturate it).
      color: waxColor,
      emissive: waxEmissive,
      emissiveIntensity: 1.7,
      roughness: 0.45,
      metalness: 0.0,
    });
    this.mc = new MarchingCubes(resolution, waxMat, false, false, 30_000);
    // Volume occupies most of the vessel interior, vertically a touch
    // smaller so wax doesn't touch the neck or the bulb-housing top.
    const innerRadius = vesselRadius * 1.65;  // 0..1 maps to centered ±scale/2
    const innerHeight = height * 0.94;
    this.mc.scale.set(innerRadius, innerHeight, innerRadius);
    this.mc.position.set(0, baseHeight + height / 2, 0);
    // The MC bounding cube is rendered against the back of the glass, so
    // disable frustum culling — otherwise an off-axis camera can clip it.
    this.mc.frustumCulled = false;
    this.add(this.mc);

    // ---- Blob state ----
    // Positions in MC-local space, where [0..1]³ is the rendered volume.
    // Most blobs start hot near the bottom — they'll begin by rising.
    this.blobs = [];
    for (let i = 0; i < blobCount; i++) {
      this.blobs.push({
        x: 0.35 + Math.random() * 0.30,
        y: 0.05 + Math.random() * 0.20,
        z: 0.35 + Math.random() * 0.30,
        vy: 0,
        strength: 0.42 + Math.random() * 0.14,
        // Strength of the field per blob. Higher = bigger globule.
        // Temperature (0=cool, 1=hot). Mostly start warm.
        temp: 0.75 + Math.random() * 0.25,
        swayPhase: Math.random() * Math.PI * 2,
        swayFreq: 0.4 + Math.random() * 0.3,
        homeX: 0.35 + Math.random() * 0.30,
        homeZ: 0.35 + Math.random() * 0.30,
      });
    }

    // ---- Bulb light ----
    this.bulbLight = new THREE.PointLight(bulbColor, bulbIntensity, 16, 1.5);
    this.bulbLight.position.set(0, baseHeight * 0.7, 0);
    this.add(this.bulbLight);
    this.bulbLight.userData.targetIntensity = bulbIntensity;

    this.clock = 0;
  }

  update(dt) {
    this.clock += dt;
    // Cap dt so a slow frame doesn't catapult blobs into the cap.
    const stepDt = Math.min(dt, 1 / 30);

    // Heat-rate is FAST at the bottom, cool-rate is SLOW at the top —
    // this is what biases the blob population toward "currently rising"
    // and reproduces the real-lava-lamp "mostly go up" rhythm.
    const HEAT_RATE = 1.2;
    const COOL_RATE = 0.18;

    for (const b of this.blobs) {
      // Heat / cool zones
      if (b.y < 0.18) b.temp = Math.min(1, b.temp + HEAT_RATE * stepDt);
      else if (b.y > 0.82) b.temp = Math.max(0, b.temp - COOL_RATE * stepDt);

      // Buoyancy biased upward — neutral point at temp=0.3 means even
      // medium-warm blobs still rise. Gravity is gentle so even cool
      // blobs sink gradually rather than plummet.
      const buoyancy = (b.temp - 0.30) * 1.6;
      const gravity = -0.55;
      b.vy += (buoyancy + gravity) * stepDt;
      b.vy *= Math.pow(0.84, stepDt * 60);

      b.y += b.vy * stepDt;

      // Ends — sticky landings (so blob spends a moment hot at the
      // bottom or cool at the top before reversing). Bouncier energy
      // would make the lamp feel mechanical.
      if (b.y < 0.06) {
        b.y = 0.06;
        b.vy = Math.max(0, b.vy);
        b.temp = 1.0;
      } else if (b.y > 0.94) {
        b.y = 0.94;
        b.vy = Math.min(0, b.vy);
        b.temp = 0.0;
      }

      // Gentle horizontal sway around home, scaled by how active the
      // blob is (rising/falling blobs sway more; stationary blobs don't).
      const sway = 0.06 * Math.min(1, Math.abs(b.vy) * 4);
      b.x = b.homeX + sway * Math.sin(this.clock * b.swayFreq + b.swayPhase);
      b.z = b.homeZ + sway * Math.cos(this.clock * b.swayFreq * 0.7 + b.swayPhase * 1.4);
    }

    // Rebuild the isosurface from the current metaball positions
    this.mc.reset();
    const subtract = 12;
    for (const b of this.blobs) {
      this.mc.addBall(b.x, b.y, b.z, b.strength, subtract);
    }
    this.mc.update();
  }

  setBulbIntensity(value) {
    this.bulbLight.intensity = value;
  }
}
